### PR TITLE
Block Namespace Changes

### PR DESCRIPTION
**Pull request by dr-dirt**
- Base namespace changed to 'nedesigns'
- Add subtype 'block' to scenery_small
- Add texture/theme fields (brick and castle) to block organization
- Add '_square' specifier to blocks
- Change '_round' specifier to '_curved'

### CODE REVIEW

**Comment by spacek531** [comment]
I like the change to the lower hierarchy. I don't know about the change from nedesigns to ne. I like the 'corner_in' and 'corner_out' standard.

**Comment by dr-dirt** [comment]
also of note: this does change 'Stucco' to 'Castle' as far as texturing goes.  I think the base game uses 'Castle' as the texture of several walls in that scenery group.  This change would reflect that; however, it does potentially group some custom objects with NCSO if that is a concern to distinguish.

**Comment by spacek531** [comment]
Do you know which custom objects would be grouped with NCSO?

**Comment by dr-dirt** [comment]
I think for example this would put castle blocks next to the castle towers and things like that.  Those blocks were called castle texture by Toon and is recognized as that texture more widely I think.

**Pull request merged**
